<?php
use LW\OrderSync\ViewModel\LogData;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * @var $block Template
 * @var $viewModel LogData
 * @var $escaper Escaper
 */

$viewModel = $block->getData('view_model');

$items =  $viewModel->getLogItems();
?>

<?php if (count($items)) {
    ?>
    <div class="table-wrapper log-history">
        <table class="data table">
            <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?php echo __('Log ID') ?></th>
                <th scope="col" class="col order_id"><?php echo __('Order ID') ?></th>
                <th scope="col" class="col return_code"><?php echo __('Return Code') ?></th>
                <th scope="col" class="col created_at"><?php echo __('Created At') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($items as $item): ?>
                <tr>
                    <td data-th="<?= $escaper->escapeHtml(__('Log ID')) ?>" class="col id">
                        <?= $escaper->escapeHtml($item->getId()) ?>
                    </td>
                    <td data-th="<?= $escaper->escapeHtml(__('Order ID')) ?>" class="col order_id">
                        <?= $escaper->escapeHtml($item->getOrderId()) ?>
                    </td>
                    <td data-th="<?= $escaper->escapeHtml(__('Return Code')) ?>" class="col return_code">
                        <?= $escaper->escapeHtml($item->getReturnCode()) ?>
                    </td>
                    <td data-th="<?= $escaper->escapeHtml(__('Created At')) ?>"
                        class="col created_at"><?=  $escaper->escapeHtml(date('Y-m-d h:m:s', strtotime($item->getCreatedAt()))); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php
}
